version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: mini_kanban_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - mini_kanban_db:/var/lib/postgresql/data

volumes:
  mini_kanban_db: